before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: olEXNd3SeBVi9+8dwXJDqcc06Im51+3WwzAM6NWB7V20i/SOkZXKtuNDtpaGjfYpMPOTr5q489If+g+3KvQ9A/NwxTtvNtceXIDl4UdEv+d+KUhnlj1XUAbooMyk4gJOosD8iBOoegZEaR8Gc+Ehw4K8z5QzYLR/ngrV22VFLtaaPO69mRzL+FMf636ackmQnXaNmV8aq8XId6v60nYudrOZRSe1ljvLx3xfC5eUDzO27OWDJZILpSINmzsUVhMk+W7kjsvAODOSH06ZRwuDTDeli03I1VjjYGeCWM6Qd4+lSn/T4OQO5qgocRNENNKL58hZDb1chVQk88TRq/aqxcWr35Bqfe0LHf5faGse3Qd473OX3khtdyMAY9PyfZTrFArhWRuRs0CLXUaLyWV29baoLf+Wk3ygkH6ul36Wn7Uf+iFObiVCxPDTbzEDkmaZjPw9ons2BHNVODsS0lKqYkHSxTthBat1x0PcWnuraA69jtMmJEBQ0p4MiPr/+DPty3T0ffA1F71uBSGT/1t9i62cSf9dsP+m9N+A+mTVYIwcbeqOagXrUx+VOCxUCKdqp8mj7YPT7T4PNXo8eqtLkjuNBL2kVHrifRJTVTS1pz1ngUuFm4xB8aktziJo7AznV/zYpA0+vDNiLbKTGiXVcA7yNAt0mrX1Xa9z+7nidY8= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
